[versions]
kotlin = "1.6.21"
ktx-serialization = "1.3.3"
ktx-coroutines = "1.6.2"
ktx-atomicfu = "0.17.2"
ktx-datetime = "0.3.2"
exposed = "0.37.3"
koin = "3.2.0"
grpc = "1.45.0"
grpcKotlin = "1.2.1"
protobuf = "3.19.4"
log4j = "2.17.2"
ktor = "2.0.2"
jackson = "2.13.2"
snowflake-id = "0.0.1"
docker-java = "3.2.13"
hoplite = "2.3.1"
plugin-protobuf = "0.8.18"
plugin-shadowjar = "7.1.2"

[libraries.kotlin-test]
module = "org.jetbrains.kotlin:kotlin-test"
version.ref = "kotlin"

[libraries.ktx-atomicfu]
module = "org.jetbrains.kotlinx:atomicfu"
version.ref = "ktx-atomicfu"

[libraries.ktx-datetime]
module = "org.jetbrains.kotlinx:kotlinx-datetime"
version.ref = "ktx-datetime"

[libraries.ktx-serialization-json]
module = "org.jetbrains.kotlinx:kotlinx-serialization-json"
version.ref = "ktx-serialization"

[libraries.ktx-serialization-core]
module = "org.jetbrains.kotlinx:kotlinx-serialization-core"
version.ref = "ktx-serialization"

[libraries.ktx-coroutines-core]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core"
version.ref = "ktx-coroutines"

[libraries.koin-core]
module = "io.insert-koin:koin-core"
version.ref = "koin"

[libraries.koin-test]
module = "io.insert-koin:koin-test"
version.ref = "koin"

[libraries.koin-ktor]
module = "io.insert-koin:koin-ktor"
version.ref = "koin"

[libraries.grpc-netty]
module = "io.grpc:grpc-netty"
version.ref = "grpc"

[libraries.grpc-testing]
module = "io.grpc:grpc-testing"
version.ref = "grpc"

[libraries.grpc-kotlin-stub]
module = "io.grpc:grpc-kotlin-stub"
version.ref = "grpcKotlin"

[libraries.grpc-protobuf]
module = "io.grpc:grpc-protobuf"
version.ref = "grpc"

[libraries.log4j-core]
module = "org.apache.logging.log4j:log4j-core"
version.ref = "log4j"

[libraries.dockerJava]
module = "com.github.docker-java:docker-java"
version.ref = "docker-java"

[libraries.dockerJava-transport-okhttp]
module = "com.github.docker-java:docker-java-transport-okhttp"
version.ref = "docker-java"

[libraries.ktor-server-cio]
module = "io.ktor:ktor-server-cio"
version.ref = "ktor"

[libraries.ktor-server-core]
module = "io.ktor:ktor-server-core"
version.ref = "ktor"

[libraries.ktor-server-host-common]
module = "io.ktor:ktor-server-host-common"
version.ref = "ktor"

[libraries.ktor-server-feature-resources]
module = "io.ktor:ktor-server-resources"
version.ref = "ktor"

[libraries.ktor-server-feature-defaultheaders]
module = "io.ktor:ktor-server-default-headers"
version.ref = "ktor"

[libraries.ktor-server-feature-autoheadresponse]
module = "io.ktor:ktor-server-auto-head-response"
version.ref = "ktor"

[libraries.ktor-server-feature-calllogging]
module = "io.ktor:ktor-server-call-logging"
version.ref = "ktor"

[libraries.ktor-server-feature-content-negotiation]
module = "io.ktor:ktor-server-content-negotiation"
version.ref = "ktor"

[libraries.ktor-server-feature-statuspages]
module = "io.ktor:ktor-server-status-pages"
version.ref = "ktor"

[libraries.ktor-client-feature-resources]
module = "io.ktor:ktor-client-resources"
version.ref = "ktor"

[libraries.ktor-client-feature-content-negotiation]
module = "io.ktor:ktor-client-content-negotiation"
version.ref = "ktor"

[libraries.ktor-server-test]
module = "io.ktor:ktor-server-test-host"
version.ref = "ktor"

[libraries.ktor-serialization-jackson]
module = "io.ktor:ktor-serialization-jackson"
version.ref = "ktor"

[libraries.jackson-databind]
module = "com.fasterxml.jackson.core:jackson-databind"
version.ref = "jackson"

[libraries.jackson-kotlin]
module = "com.fasterxml.jackson.module:jackson-module-kotlin"
version.ref = "jackson"

[libraries.snowflakeId]
module = "de.mkammerer.snowflake-id:snowflake-id"
version.ref = "snowflake-id"

[libraries.hoplite]
module = "com.sksamuel.hoplite:hoplite-core"
version.ref = "hoplite"

[plugins]
protobuf = { id = "com.google.protobuf", version.ref = "plugin-protobuf" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-atomicfu = { id = "org.jetbrains.kotlin.plugin.atomicfu", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadowjar = { id = "com.github.johnrengelman.shadow", version.ref = "plugin-shadowjar" }