[versions]
kotlin = "1.6.10"
ktx-serialization = "1.3.2"
ktx-coroutines = "1.6.0"
ktx-atomicfu = "0.17.0"
ktx-datetime = "0.3.2"
exposed = "0.37.3"
koin = "3.1.2"
grpc = "1.45.0"
grpcKotlin = "1.2.1"
protobuf = "3.19.4"
plugin-protobuf = "0.8.18"
log4j = "2.17.2"

[libraries.ktx-atomicfu]
module = "org.jetbrains.kotlinx:atomicfu"
version.ref = "ktx-atomicfu"

[libraries.ktx-datetime]
module = "org.jetbrains.kotlinx:kotlinx-datetime"
version.ref = "ktx-datetime"

[libraries.ktx-serialization-json]
module = "org.jetbrains.kotlinx:kotlinx-serialization-json"
version.ref = "ktx-serialization"

[libraries.ktx-coroutines-core]
module = "org.jetbrains.kotlinx:kotlinx-coroutines-core"
version.ref = "ktx-coroutines"

[libraries.koin-core]
module = "io.insert-koin:koin-core"
version.ref = "koin"

[libraries.koin-test]
module = "io.insert-koin:koin-test"
version.ref = "koin"

[libraries.grpc-netty]
module = "io.grpc:grpc-netty"
version.ref = "grpc"

[libraries.grpc-testing]
module = "io.grpc:grpc-testing"
version.ref = "grpc"

[libraries.grpc-kotlin-stub]
module = "io.grpc:grpc-kotlin-stub"
version.ref = "grpcKotlin"

[libraries.grpc-protobuf]
module = "io.grpc:grpc-protobuf"
version.ref = "grpc"

[libraries.log4j-core]
module = "org.apache.logging.log4j:log4j-core"
version.ref = "log4j"

[plugins]
protobuf = { id = "com.google.protobuf", version.ref = "plugin-protobuf" }