version: "3.7"
services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: PAPER
      VERSION: 1.9.4
      CONSOLE: "false"
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - minecraft:/data
volumes:
  minecraft: