version: "3.7"
services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: PAPER
      VERSION: latest
      CONSOLE: "false"
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - minecraft:/data
    tty: true
      stdin_open: true
      restart: always
volumes:
  minecraft: